Add tests

diff --git a/.github/workflows/api-pipeline.yaml b/.github/workflows/api-pipeline.yaml
--- a/.github/workflows/api-pipeline.yaml
+++ b/.github/workflows/api-pipeline.yaml
@@ -37,4 +37,8 @@ jobs:
 
       - name: Run Tests (Optional)
         run: |
-          echo "Add Postman/Newman/Integration tests here"
+          apictl get apis -e dev --insecure | awk 'NR>1 {print}' | grep -E "ShopKartAPI" || {
+            echo "ShopKartAPI not found in Publisher (dev)."
+            exit 1
+          }
+          echo "ShopKartAPI is present in Publisher (dev)"
